# Email Service
# =============
# Send equity research reports via email

import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from config import settings

logger = logging.getLogger(__name__)

class EmailService:
    """
    Service to send reports via email using SMTP.
    """
    
    def __init__(self):
        self.host = settings.SMTP_HOST
        self.port = settings.SMTP_PORT
        self.user = settings.SMTP_USER
        self.password = settings.SMTP_PASSWORD
        self.from_email = settings.FROM_EMAIL

    def send_report(self, to_email: str, subject: str, content: str, is_html: bool = False) -> bool:
        """
        Send an email with report content.
        """
        if not self.user or not self.password:
            logger.error("SMTP credentials not configured. Please set SMTP_USER and SMTP_PASSWORD in .env")
            return False

        try:
            msg = MIMEMultipart()
            msg['From'] = self.from_email
            msg['To'] = to_email
            msg['Subject'] = subject

            # Attach content
            msg.attach(MIMEText(content, 'html' if is_html else 'plain'))

            # Connect and send
            with smtplib.SMTP(self.host, self.port) as server:
                server.starttls()
                server.login(self.user, self.password)
                server.send_message(msg)
            
            logger.info(f"Email sent successfully to {to_email}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email to {to_email}: {e}")
            return False

    def format_report_html(self, report_data: dict) -> str:
        """
        Format report data into a clean HTML email template.
        """
        ticker = report_data.get("ticker", "N/A")
        analysis = report_data.get("analysis", "")
        
        # Very basic conversion of markdown to simple HTML bits for email
        # In a real app, we'd use a markdown library or template
        html_content = f"""
        <html>
            <body style="font-family: sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h1 style="color: #2563eb;">Equity Research Report: {ticker}</h1>
                    <p style="color: #666; font-size: 0.9em;">Generated on: {report_data.get("date", "N/A")}</p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <div style="white-space: pre-wrap;">
                        {analysis}
                    </div>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 0.8em; color: #999;">This report was generated by AI Equity Research Platform.</p>
                </div>
            </body>
        </html>
        """
        return html_content

# Singleton instance
email_service = EmailService()
